Fix backward compatibility in pickle_deserialize_old_knownnodes()
Bitmessage/PyBitmessage pull request #1668
Opened 2020-09-14 14:43 UTC by g1itch

Hello!

#1662 is caused by changed package structure. Here I've set up a minimal upgrade from v0.6.3 to reproduce the bug.

2020-09-14 15:36 UTC, g1itch commented
I'm going to squash e2673fb with d8099fd when you check the failure.

2020-10-03 10:41 UTC, navjotcis commented
I was testing PR and faces this issue on logs
![Uploading image.png…]()

2020-10-03 11:04 UTC, g1itch commented
> I was testing PR and faces this issue on logs.
> ![image](https://user-images.githubusercontent.com/33522186/94989560-6a7f6f80-0593-11eb-8171-74071139148a.png)

It is #1661, the bug, present in current v0.6.

2020-10-23 11:44 UTC, PeterSurda commented
can you rebase this on top of #1683 when ready?

2020-10-28 08:00 UTC, PeterSurda commented on .travis.yml
> +    sleep 10;
How about instead we simply include a copy of old-format `knownnodes.dat`, and the test will put it into the config directory inside `setUp` and remove it during `tearDown`?

2020-10-28 08:02 UTC, PeterSurda requested changes
I think the test should be done in a diffent manner. Maybe an additional test for old-style pickle, which will use a static file which will be included in the PR.

2020-12-22 08:06 UTC, closed without merging