implemented filter query in sent table on the bases of folder= 'sent'
Bitmessage/PyBitmessage pull request #1672
Opened 2020-09-19 12:04 UTC by navjotcis

I have implemented a filter query for the sent table on the bases of folder ='sent' because in  kivy app there is one more feature draft message so for storing draft message they are using the same table sent only the folder value is change on the bases of folder type so I have implemented all the sent table filter query in class_singleWorker.py and class_singleCleaner.py files.

2020-10-13 07:53 UTC, PeterSurda requested changes

2020-10-13 07:53 UTC, PeterSurda commented on src/class_singleWorker.py
> +                ' WHERE ackdata=? AND folder="sent" ',
Single quotes: ` AND folder='sent' `

2020-10-13 07:53 UTC, PeterSurda commented on src/class_singleWorker.py
> -
why?

2020-10-14 15:22 UTC, navjotcis commented on src/class_singleWorker.py
> +                ' WHERE ackdata=? AND folder="sent" ',
ok

2020-10-23 11:29 UTC, PeterSurda approved these changes

2020-10-31 09:10 UTC, merged