replace print statements with logger
Bitmessage/PyBitmessage pull request #1688
Opened 2020-11-12 17:13 UTC by navjotcis

I have replaced print statement with logger in the below given module
> network/randomtrackingdict.py
> singleinstance.py
> singleinstance.py
Fixes #1373

2020-11-16 08:10 UTC, PeterSurda requested changes
- the test in randomtrackingdict should be refactored as a unit test
- remove singleinstnace from PR
- filesystem is OK

2020-11-16 21:03 UTC, PeterSurda requested changes
Move tests into unit tests.

2020-11-21 10:12 UTC, PeterSurda commented
- remove main section from `randomtrackingdict.py`
- fix errors reported by travis

2020-12-19 19:01 UTC, PeterSurda requested changes
Please do the requested changes and fix code quality.

2020-12-19 19:01 UTC, PeterSurda commented on src/tests/test_randomtrackingdict.py
> +        for x in range(len(a) - 1):
This is debugging information. We should check if this is not too slow. Let's say all values of `a[x + 1] - a[x]` need to be less than `10.0`.

2020-12-19 19:05 UTC, PeterSurda commented
Also you can't write "Fixes #xxxxx" unless it's a complete fix, that screws up the dependency tracking.

2020-12-22 07:38 UTC, navjotcis commented
I have made the suggested changes not it is ready to merge.

2020-12-22 08:10 UTC, PeterSurda requested changes
Please fix import.

2020-12-22 08:10 UTC, PeterSurda commented on src/tests/test_randomtrackingdict.py
> +        """Check the logic of RandomTrackingDict class"""
`"""Test performance of RandomTrackingDict"""`

2020-12-22 08:10 UTC, PeterSurda commented on src/tests/test_randomtrackingdict.py
> +            self.assertLess(a[x + 1] - a[x], 10)
Maybe this needs to be `10.0`, I'm not fully sure, we'll see once the import is fixed.

2020-12-25 08:22 UTC, PeterSurda requested changes
fix

2020-12-25 08:22 UTC, PeterSurda commented on src/network/__init__.py
> +from .randomtrackingdict import RandomTrackingDict
why dot at the beginning?

2020-12-25 15:15 UTC, navjotcis commented on src/network/__init__.py
> +from .randomtrackingdict import RandomTrackingDict
checking with every possible way

2020-12-29 08:04 UTC, closed without merging