test case for openclpow module
Bitmessage/PyBitmessage pull request #1718
Opened 2021-01-16 18:59 UTC by navjotcis

2021-01-18 07:54 UTC, PeterSurda requested changes
Good start, fix CQ, add `@skipTestIf` so that it skips it if opencl isn't avaialble.

2021-01-19 11:43 UTC, PeterSurda requested changes
change the skip decorator, otherwise ok

2021-01-19 11:43 UTC, PeterSurda commented on src/tests/test_openclpow.py
> +    @unittest.skipIf(not openclpow.libAvailable,
@unittest.skipIf(not openclpow.enabledGpus,
                                "No GPUs found / enabled")

2021-01-19 11:45 UTC, PeterSurda commented
Actually, now that I think about it, it's more complicated. You need to put `initCL` into `setupClass`.

2021-01-19 18:47 UTC, navjotcis commented
in which module `setupClass` is present?

2021-01-21 08:30 UTC, PeterSurda approved these changes

2021-01-21 20:21 UTC, merged

2021-01-29 17:20 UTC, g1itch commented
I don't understand why is this test case subclassed from TestProcessProto.

2021-01-30 15:04 UTC, PeterSurda commented
@g1itch You're right. I'll request a fix.

2021-01-30 15:20 UTC, g1itch commented
> @g1itch You're right. I'll request a fix.

ec6f078