remove TestProcessProto import from test_openclpow module
Bitmessage/PyBitmessage pull request #1726
Opened 2021-02-01 09:38 UTC by navjotcis

remove the use of TestProcessProto from the test_openclpow module

2021-02-02 14:42 UTC, g1itch commented on src/tests/test_openclpow.py
> +import pybitmessage.openclpow as openclpow
```from pybitmessage import openclpow```

2021-02-02 14:43 UTC, g1itch requested changes
Please rebase to v0.6

2021-02-04 09:04 UTC, navjotcis commented
rebased

2021-02-04 09:53 UTC, PeterSurda approved these changes
Looks ok to me

2021-02-04 13:01 UTC, g1itch approved these changes
OK, I'll merge

2021-02-04 13:02 UTC, merged