Add sqlite functions while versioning
Bitmessage/PyBitmessage pull request #1740
Opened 2021-03-06 14:36 UTC by cis-muzahid

## Repository contributions to the PyBitmessage project

- You can get paid for merged commits if you register at [Tip4Commit](https://tip4commit.com/github/Bitmessage/PyBitmessage)

### Code

- Try to refer to github issue tracker or other permanent sources of discussion about the issue.
- It is clear from the diff *what* you have done, it may be less clear *why* you have done it so explain why this change is necessary rather than what it does

### Documentation

- If there has been a change to the code, there's a good possibility there should be a corresponding change to the documentation 
- If you can't run `fab build_docs` successfully, ask for someone to run it against your branch

### Tests

- If there has been a change to the code, there's a good possibility there should be a corresponding change to the tests
- If you can't run `fab tests` successfully, ask for someone to run it against your branch

## Translations

- For helping with translations, please use [Transifex](https://www.transifex.com/bitmessage-project/pybitmessage/).
- There is no need to submit pull requests for translations.
- For translating technical terms it is recommended to consult the [Microsoft Language Portal](https://www.microsoft.com/Language/en-US/Default.aspx).

### Gitiquette

- Make the pull request against the ["v0.6" branch](https://github.com/Bitmessage/PyBitmessage/tree/v0.6)
- PGP-sign the commits included in the pull request
- Use references to tickets, e.g. `addresses #123` or `fixes #234` in your commit messages
- Try to use a good editor that removes trailing whitespace, highlights potential python issues and uses unix line endings
- If for some reason you don't want to use github, you can submit the patch using Bitmessage to the "bitmessage" chan, or to one of the developers.

2021-03-07 12:21 UTC, PeterSurda requested changes
- [ ] test direct updates, without `SELECT`
- [ ] make exception more specific and if needed, split it into 2, one for old python, one for old sqlite
- [ ] make the creation of custom function a separate method. This way you can also simplify setup and don't need to start the thread in the test. It would be a more tight unit test.
- [ ] use and check an actual address rather than just if it puts a record into the database.

2021-03-08 07:56 UTC, PeterSurda commented on src/class_sqlThread.py
> +            except Exception as err:
`sqlite.NotSupportedError` for old sqlite, `TypeError` for old python

2021-03-10 08:27 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlLookup.start()
add `sql_ready.wait()`

2021-03-10 08:27 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +from ..helper_sql import sqlStoredProcedure
als import `sql_ready`

2021-03-10 13:28 UTC, PeterSurda requested changes
test direct updates and do the other things I mentioned.

2021-03-10 13:28 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        self.assertNotEqual(hsh, 1, "test case fail for create_function")
test content validity, not just if an entry exists.

2021-03-10 13:28 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        except Exception as err:
here also the two exceptions like in `class_sqlThread`

2021-03-10 13:28 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +    def test_create_function(self):
there should be a separate method for creating, and it should be either in `helper_sql` or in `class_sqlThread`. Here it should only test whether it works, not create the function again

2021-03-10 13:28 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        except Exception as err:
this should be cleaned up so that an exception can simply be ignored and treated as a failure by the test suite

2021-03-10 13:28 UTC, PeterSurda commented on src/class_sqlThread.py
> +            # create_function
this should be a separate method/function, either in `helper_sql` or elsewhere in this file.

2021-03-11 14:41 UTC, PeterSurda commented on src/helper_sql.py
> +def executeCF(conn):
docstring missing

2021-03-11 14:43 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        executeCF(self.conn)
I don't think this is necessary as it's created by the sql thread already.

2021-03-11 14:44 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        encoded_str = encodeAddress(1, 1, "21122112211221122112")
these should be class variables or constants defined elsewhere.

Also version should be 4.

2021-03-11 14:44 UTC, PeterSurda commented on src/tests/sql/create_function.sql
> +INSERT INTO testhash (addressversion, hash) VALUES(1, "21122112211221122112");
addressversion should be 4

2021-03-11 14:45 UTC, PeterSurda commented on src/helper_sql.py
> +def executeCF(conn):
Also I think this would be better inside `class_sqlThread`. This function doesn't need to be called from other places.

2021-03-11 14:45 UTC, PeterSurda requested changes
please make the requested changes

2021-03-14 17:23 UTC, PeterSurda requested changes

2021-03-14 17:23 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        self.conn.execute('''DROP TABLE testhash;''')
`sqlExecute('''DROP TABLE testhash''')`

2021-03-14 17:23 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        query = sqlExecute('''select address from testhash;''')
remove `;`

2021-03-14 17:23 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlExecute('''UPDATE testhash SET address=(select enaddr(testhash.addressversion, 1, hash)) WHERE hash=testhash.hash;  ''')
remove `;`

2021-03-14 17:23 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlExecute('''INSERT INTO testhash (addressversion, hash) VALUES(4, "21122112211221122112");''')
remove `;`

2021-03-14 17:23 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +    conn = sqlite3.connect(appdata + 'messages.dat')
Remove lines 20-22.

2021-03-14 17:23 UTC, PeterSurda commented on src/class_sqlThread.py
> +            try:
The function is created only when upgrading from version 9 to version 10. This is probably why the tests raise an exception. It should be created always. Perhaps right after creating the cursor.

2021-03-14 17:23 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        self.assertNotEqual(hsh, 1, "test case fail for create_function")
I'm not sure this (line 81) actually tests anything. Remove.

2021-03-14 17:23 UTC, PeterSurda commented on src/class_sqlThread.py
> +            try:
This section should also be a separate method inside the class

2021-03-15 11:15 UTC, PeterSurda commented on src/class_sqlThread.py
> +        # self.conn = sqlite3.connect(state.appdata + 'messages.dat')
remove these lines

2021-03-15 11:16 UTC, PeterSurda commented on src/class_sqlThread.py
> +            self.cur.execute('''UPDATE pubkeys SET address=(select enaddr(pubkeys.addressversion, 1, hash)) WHERE hash=pubkeys.hash; ''')
direct update, not joined.

2021-03-15 11:17 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlExecute('''UPDATE testhash SET address=(select enaddr(testhash.addressversion, 1, hash)) WHERE hash=testhash.hash''')
direct update, not join

2021-03-15 11:20 UTC, PeterSurda commented on src/class_sqlThread.py
> +        except (TypeError, sqlite3.NotSupportedError) as err:
I think this isn't correct, as xenial returns this:
`2021-03-15 11:28:56,156 - ERROR - Got error while pass deterministic in sqlite create function function takes at most 3 arguments (4 given), Passing 3 params`

2021-03-15 11:20 UTC, PeterSurda commented
Also fix python3 tests (skip).

2021-03-15 14:19 UTC, PeterSurda commented on src/class_sqlThread.py
> +        except (TypeError, sqlite3.NotSupportedError) as err:
My bad. Just downgrade the log to debug severity.

2021-03-15 15:20 UTC, PeterSurda requested changes

2021-03-15 15:20 UTC, PeterSurda commented on src/helper_sql.py
> +    import queue as Queue #python2
this should say `# python3`

2021-03-15 15:20 UTC, PeterSurda commented on src/helper_sql.py
> +    import Queue #python3
`# python2

2021-03-15 15:20 UTC, PeterSurda commented on src/class_sqlThread.py
> +            logger.error(
downgrade to `logger.debug`

2021-03-15 15:39 UTC, PeterSurda approved these changes
I approve, just the python3 compatibility needs to be fixed in `class_sqlThread.py` and `bmconfigparser.py` in a separate PR before this can be merged.

2021-04-28 08:16 UTC, PeterSurda commented
@cis-muzahid  Please confirm this is obsolete.

2021-05-28 13:10 UTC, g1itch commented
This duplicates merged #1751

2021-05-28 13:10 UTC, closed without merging