Add `enaddr` sqlite function for encoding a bitmessage address
Bitmessage/PyBitmessage pull request #1751
Opened 2021-04-07 12:57 UTC by cis-muzahid

## Repository contributions to the PyBitmessage project

- You can get paid for merged commits if you register at [Tip4Commit](https://tip4commit.com/github/Bitmessage/PyBitmessage)

### Code

- Try to refer to github issue tracker or other permanent sources of discussion about the issue.
- It is clear from the diff *what* you have done, it may be less clear *why* you have done it so explain why this change is necessary rather than what it does

### Documentation

- If there has been a change to the code, there's a good possibility there should be a corresponding change to the documentation 
- If you can't run `fab build_docs` successfully, ask for someone to run it against your branch

### Tests

- If there has been a change to the code, there's a good possibility there should be a corresponding change to the tests
- If you can't run `fab tests` successfully, ask for someone to run it against your branch

## Translations

- For helping with translations, please use [Transifex](https://www.transifex.com/bitmessage-project/pybitmessage/).
- There is no need to submit pull requests for translations.
- For translating technical terms it is recommended to consult the [Microsoft Language Portal](https://www.microsoft.com/Language/en-US/Default.aspx).

### Gitiquette

- Make the pull request against the ["v0.6" branch](https://github.com/Bitmessage/PyBitmessage/tree/v0.6)
- PGP-sign the commits included in the pull request
- Use references to tickets, e.g. `addresses #123` or `fixes #234` in your commit messages
- Try to use a good editor that removes trailing whitespace, highlights potential python issues and uses unix line endings
- If for some reason you don't want to use github, you can submit the patch using Bitmessage to the "bitmessage" chan, or to one of the developers.

2021-04-07 14:33 UTC, PeterSurda requested changes
I think `WHERE` can be removed.

Python 3 tests fail due to `src.queues.py` not being python3 compatible.

The rest looks ok but I'll re-check once the existing problems are fixed.

2021-04-07 14:33 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlExecute('''UPDATE testhash SET address=(enaddr(testhash.addressversion, 1, hash)) WHERE hash=testhash.hash''')
why is there a `WHERE`, can't we skip it?

2021-04-07 14:33 UTC, PeterSurda commented on src/class_sqlThread.py
> +            # replica for loop to update hashed address
why `WHERE`?

2021-04-12 11:50 UTC, PeterSurda commented
bitmessagecli can be put into a separate PR.

2021-04-12 11:55 UTC, PeterSurda requested changes
- please make the changes requested
- fix python3

2021-04-12 11:55 UTC, PeterSurda commented on src/bmconfigparser.py
> +                except (KeyError, ValueError, AttributeError) as e:
I think the original is more correct

2021-04-12 11:55 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlStoredProcedure('exit')
you should also
`sqlLokup.join()`

2021-04-12 11:55 UTC, PeterSurda commented on src/tests/test_sqlthread.py
> +        sqlStoredProcedure('exit')
or set `sqlLookup.daemon = true`, that should work instead too.

2021-04-23 12:11 UTC, PeterSurda requested changes
Please respond to comments and make the requested changes.

2021-04-23 12:11 UTC, PeterSurda commented on src/bmconfigparser.py
> +    """Singleton class inherited from ConfigParsedadfeConfigParser
why

2021-04-23 12:11 UTC, PeterSurda commented on src/bmconfigparser.py
> +        def addresses(self, hidden=False):
why not `@staticmethod`?

2021-04-23 12:11 UTC, PeterSurda commented on src/bmconfigparser.py
> +        def paymentaddress(self):
what is this

2021-04-23 12:30 UTC, cis-muzahid commented on src/bmconfigparser.py
> +    """Singleton class inherited from ConfigParsedadfeConfigParser
I will remove this

2021-04-23 12:31 UTC, cis-muzahid commented on src/debug.py
> +try:
Okay I will apply and test

2021-04-27 08:08 UTC, PeterSurda approved these changes

2021-04-27 08:08 UTC, merged