Added flatpak build manifests with split dependencies
Bitmessage/PyBitmessage pull request #1755
Opened 2021-04-27 17:41 UTC by kdcis

## Repository contributions to the PyBitmessage project

- You can get paid for merged commits if you register at [Tip4Commit](https://tip4commit.com/github/Bitmessage/PyBitmessage)

### Code

- Try to refer to github issue tracker or other permanent sources of discussion about the issue.
- It is clear from the diff *what* you have done, it may be less clear *why* you have done it so explain why this change is necessary rather than what it does

### Documentation

- If there has been a change to the code, there's a good possibility there should be a corresponding change to the documentation 
- If you can't run `fab build_docs` successfully, ask for someone to run it against your branch

### Tests

- If there has been a change to the code, there's a good possibility there should be a corresponding change to the tests
- If you can't run `fab tests` successfully, ask for someone to run it against your branch

## Translations

- For helping with translations, please use [Transifex](https://www.transifex.com/bitmessage-project/pybitmessage/).
- There is no need to submit pull requests for translations.
- For translating technical terms it is recommended to consult the [Microsoft Language Portal](https://www.microsoft.com/Language/en-US/Default.aspx).

### Gitiquette

- Make the pull request against the ["v0.6" branch](https://github.com/Bitmessage/PyBitmessage/tree/v0.6)
- PGP-sign the commits included in the pull request
- Use references to tickets, e.g. `addresses #123` or `fixes #234` in your commit messages
- Try to use a good editor that removes trailing whitespace, highlights potential python issues and uses unix line endings
- If for some reason you don't want to use github, you can submit the patch using Bitmessage to the "bitmessage" chan, or to one of the developers.

2021-04-28 08:08 UTC, PeterSurda requested changes
Please remove the extra lines from build sequence

2021-04-28 08:08 UTC, PeterSurda commented on packages/flatpak/org.bitmessage.PyBitmessage.json
> +          "python checkdeps.py",
lines 26 - 29 aren't necessary

2021-04-28 08:08 UTC, PeterSurda commented on packages/flatpak/org.bitmessage.PyBitmessage.json
> +          "cat /app/bin/pybitmessage",
this isn't necessary

2021-04-30 13:03 UTC, kdcis commented
Removed extra lines from build sequence,
Updated Description,
Rebase done,
Added Build instructions under ```docs``` directory.

2021-05-27 13:10 UTC, closed without merging