Python3 port for openclpow.py, test_openclpow.py
Bitmessage/PyBitmessage pull request #1790
Opened 2021-07-22 12:09 UTC by kdcis

### Enabled Python3

2021-07-28 08:00 UTC, PeterSurda commented on src/openclpow.py
> +try:
Again I need to investigate this like in other PRs.

2021-07-28 08:01 UTC, PeterSurda reviewed
I need to think about imports, rest is ok.

2021-07-28 13:46 UTC, g1itch commented
Do you have an AMD graphics card? Did you ran the test?

2021-07-28 16:23 UTC, PeterSurda commented
@g1itch The servers running the buildbot workers all have AMD GPUs or APUs, but the VMs/containers don't have access to it, yet. For the time being, I could run the test manually just to check.

2021-07-28 16:49 UTC, g1itch commented
> @g1itch The servers running the buildbot workers all have AMD GPUs or APUs, but the VMs/containers don't have access to it, yet. For the time being, I could run the test manually just to check.

cool, I've already started to think about buying some PCI-X GPU...

2021-08-11 09:01 UTC, PeterSurda approved these changes

2021-08-11 13:12 UTC, g1itch commented
Bad signatures! This wont merge.

2021-08-13 11:10 UTC, g1itch requested changes
Bad signature!

2021-08-13 12:11 UTC, kdcis commented
> Bad signature!

Signature updated.

2021-08-13 12:43 UTC, g1itch requested changes
Please, rebase

2021-08-13 16:00 UTC, g1itch approved these changes

2021-08-13 16:01 UTC, merged