Python3 port for test_config_process.py
Bitmessage/PyBitmessage pull request #1797
Opened 2021-08-02 11:35 UTC by kdcis

- Enabled Python3

- Fix warning: Unclosed File Error

2021-08-11 08:59 UTC, PeterSurda requested changes

2021-08-11 08:59 UTC, PeterSurda commented on src/tests/test_process.py
> -            return open(pfile, 'rb').readline().strip()
good

2021-08-11 08:59 UTC, PeterSurda commented on src/pybitmessage
> -execfile(script_file, new_globals)
This is probably ok, but other parts of the code refuse to run in python3, or may be not compatible. If you remove the refusals, you'll get more errors and those need to be fixed. However, maybe it makes sense to fix those first before allowing this script to run in python3 as that may be a lot of work.

2021-08-11 13:28 UTC, g1itch commented
It's a bad idea to edit this workaround artifact. The main problem is the circular import in the `network` package and not sorted side effects of such imports as `debug`, `helper_startup`. That all issues are preventing us from using the right script kwarg:  https://github.com/Bitmessage/PyBitmessage/blob/v0.6/setup.py#L171

And also you've already informed about `TestProcessProto` and the blind tests: they are going to be finished last because are using the whole pybitmessage daemon installed in the system.

2021-08-11 13:39 UTC, g1itch commented
The main idea of the fake script was to use `pathmagic` in setuptools generated script, or rather something close enough to it, not to reinvent the wheel, but this particular one is taken from gentoo `python-exec` product and it was a miracle that it works everywhere.

2021-08-12 08:22 UTC, PeterSurda commented
Only keep the bottom most change, revert everything else.

2021-08-12 12:50 UTC, kdcis commented
> Only keep the bottom most change, revert everything else.

Updated.

2021-08-13 08:13 UTC, PeterSurda requested changes
Remove first hunk, only keep second hunk.

2021-08-13 15:40 UTC, kdcis commented
> Remove first hunk, only keep second hunk.

Updated accordingly.

2021-08-18 08:41 UTC, PeterSurda approved these changes

2021-08-25 02:50 UTC, merged