Updated code quality binary operator line change & ignore bare except changes in class_objectProcessor.py
Bitmessage/PyBitmessage pull request #1808
Opened 2021-08-17 08:22 UTC by kdcis

Binary operator line change update
Ignored bare except warnings

2021-08-17 09:00 UTC, PeterSurda requested changes

2021-08-17 09:00 UTC, PeterSurda commented on src/class_objectProcessor.py
> +                except:  # noqa:E722
`safeGet`, default empty string

2021-08-17 09:00 UTC, PeterSurda commented on src/class_objectProcessor.py
> +            except:  # noqa:E722
same as above, `safeGet`, default `None`

2021-08-17 09:00 UTC, PeterSurda commented on src/class_objectProcessor.py
>              if apiNotifyPath != '':
`if apiNotifyPath:`

2021-08-17 11:52 UTC, kdcis commented on src/class_objectProcessor.py
> +                except:  # noqa:E722
Updated

2021-08-17 11:52 UTC, kdcis commented on src/class_objectProcessor.py
>                  if apiNotifyPath != '':
Updated

2021-08-17 11:52 UTC, kdcis commented on src/class_objectProcessor.py
> +                except:  # noqa:E722
Updated

2021-08-17 11:52 UTC, kdcis commented on src/class_objectProcessor.py
> +            except:  # noqa:E722
Updated

2021-08-17 11:53 UTC, kdcis commented on src/class_objectProcessor.py
>              if apiNotifyPath != '':
Updated

2021-08-18 08:28 UTC, PeterSurda approved these changes

2021-09-01 15:21 UTC, kdcis commented
Code quality changes done & merged in @g1itch 's  PR #1832

2021-09-01 15:21 UTC, closed without merging