Updated code quality range by six.moves.range functions in l10n.py
Bitmessage/PyBitmessage pull request #1837
Opened 2021-08-27 16:19 UTC by kdcis

Replaced range by six.moves.range functions

2021-08-31 08:10 UTC, PeterSurda commented
resolve merge conflicts and check if there's anything left at all in the PR.

2021-08-31 14:21 UTC, g1itch commented
> resolve merge conflicts and check if there's anything left at all in the PR.

It's about using the `range()` or `six.moves.range()`. You decide if it's needed here. The code is executed once during the program start.

2021-09-02 12:52 UTC, g1itch commented on src/l10n.py
> +from six.moves import range
isort

2021-09-03 08:25 UTC, PeterSurda requested changes

2021-09-03 08:25 UTC, PeterSurda commented on src/l10n.py
> +        except:  # noqa:E722
`except (ValueError, TypeError)`

2021-09-06 16:13 UTC, kdcis commented on src/l10n.py
> +from six.moves import range
Updated

2021-09-06 16:13 UTC, kdcis commented on src/l10n.py
> +        except:  # noqa:E722
Updated

2021-09-07 08:26 UTC, PeterSurda approved these changes

2021-09-29 13:52 UTC, PeterSurda approved these changes

2021-09-29 13:53 UTC, merged