Updated code quality added bare except warning ignore comment
Bitmessage/PyBitmessage pull request #1842
Opened 2021-09-15 16:39 UTC by kdcis

Added bare except warning ignore comment

2021-09-17 08:06 UTC, PeterSurda requested changes

2021-09-17 08:06 UTC, PeterSurda commented on src/upnp.py
>              self.extPort = BMConfigParser().getint('bitmessagesettings', 'extport')
`safeGetInt`

2021-09-27 14:24 UTC, kdcis commented on src/upnp.py
>              self.extPort = BMConfigParser().getint('bitmessagesettings', 'extport')
Updated

2021-09-28 08:35 UTC, PeterSurda approved these changes

2021-09-28 08:36 UTC, merged