Update code quality function spacing, bare except & long line changes
Bitmessage/PyBitmessage pull request #1851
Opened 2021-09-29 17:50 UTC by kdcis

Updated function spacing
Added specific exception for bare except changes 
Updated long line changes

2021-09-30 12:01 UTC, PeterSurda commented on packages/collectd/pybitmessagestatus.py
> +    pybmurl = "http://" + apiUsername + ":" + apiPassword + "@" + apiInterface + ":" + str(int(apiPort)) + "/"
use `format`

2021-09-30 12:09 UTC, PeterSurda requested changes

2021-09-30 12:09 UTC, PeterSurda commented on packages/collectd/pybitmessagestatus.py
> +    except (json.decoder.JSONDecodeError, TypeError()):
careful about python2 backwards compatibility

2021-09-30 12:09 UTC, PeterSurda commented on packages/collectd/pybitmessagestatus.py
> +    except (json.decoder.JSONDecodeError, TypeError()):
also `api.clientStatus()` may raise a different exception

2021-09-30 12:09 UTC, PeterSurda commented on packages/collectd/pybitmessagestatus.py
> +        except (NameError, KeyError):
`TypeError` instead of `NameError`

2021-10-01 11:05 UTC, kdcis commented on packages/collectd/pybitmessagestatus.py
> +    pybmurl = "http://" + apiUsername + ":" + apiPassword + "@" + apiInterface + ":" + str(int(apiPort)) + "/"
Updated

2021-10-01 11:05 UTC, kdcis commented on packages/collectd/pybitmessagestatus.py
> +    except (json.decoder.JSONDecodeError, TypeError()):
Updated

2021-10-01 12:07 UTC, PeterSurda approved these changes

2021-10-01 16:19 UTC, kdcis commented on packages/collectd/pybitmessagestatus.py
> +    except (json.decoder.JSONDecodeError, TypeError()):
updated

2021-10-01 16:20 UTC, kdcis commented on packages/collectd/pybitmessagestatus.py
> +        except (NameError, KeyError):
updated

2021-10-04 06:39 UTC, merged