kivy build run & dockerfile
Bitmessage/PyBitmessage pull request #1939
Opened 2022-03-01 05:12 UTC by surbhicis

seperate kivy build run & dockerfile

2022-03-01 06:12 UTC, PeterSurda requested changes

2022-03-01 06:12 UTC, PeterSurda commented on .buildbot/android/build.sh
> +buildozer android debug logcat run
newline at the end of file missing

2022-03-01 10:26 UTC, surbhicis commented on .buildbot/android/build.sh
> +buildozer android debug logcat run
done

2022-03-04 07:03 UTC, PeterSurda approved these changes

2022-03-04 07:04 UTC, merged