Add methods to enable/disable identity
Bitmessage/PyBitmessage pull request #1968
Opened 2022-05-05 08:00 UTC by shekhar-cis

Add method to enable & disable the identity.

2022-05-06 07:17 UTC, PeterSurda commented on src/bmconfigparser.py
> +        self.set(str(address), 'enabled', 'false')
any error handling?

2022-05-06 07:17 UTC, PeterSurda commented on src/bmconfigparser.py
> +        self.set(address, 'enabled', 'true')
also perhaps some error handling

2022-05-11 07:46 UTC, PeterSurda requested changes

2022-05-11 07:46 UTC, PeterSurda commented on src/bmconfigparser.py
> +import shared
import the function directly

2022-05-11 07:46 UTC, PeterSurda commented on src/bmconfigparser.py
> +    def search_addresses(address, searched_text):
- add a test
- convert into method

2022-05-11 07:46 UTC, PeterSurda commented on src/bmconfigparser.py
> +    def disable_address(self, address):
add a test

2022-05-11 07:46 UTC, PeterSurda commented on src/bmconfigparser.py
> +    def enable_address(self, address):
test

2022-05-13 14:16 UTC, shekhar-cis commented on src/bmconfigparser.py
> +    def enable_address(self, address):
Done

2022-05-13 14:17 UTC, shekhar-cis commented on src/bmconfigparser.py
> +    def search_addresses(address, searched_text):
Converted into method

2022-05-16 07:56 UTC, PeterSurda commented on src/bmconfigparser.py
> +        self.set(address, 'enabled', 'true')
I changed my mind.

2022-05-18 07:52 UTC, PeterSurda requested changes

2022-05-18 07:52 UTC, PeterSurda commented on src/tests/test_config_address.py
> +    #     self.assertRaises(configparser.NoSectionError, self.nonexistent.setTemp('non_existent_address', 'enabled'))
2 options, inline and context manager:
```
self.assertRaises(configparser.NoSectionError,
                              self.config.enable_address,
                              'non_existent_address')
```
```
with assertRaises(configparser.NoSectionError):
    self.config.enable_address('non_existent_address')
```

2022-05-18 07:52 UTC, PeterSurda commented on src/tests/test_config_address.py
> +        self.enabled.setTemp('enabled_address', 'enabled', 'true')
`enable_address`, not `setTemp`

2022-05-19 08:00 UTC, PeterSurda approved these changes

2022-05-19 08:01 UTC, PeterSurda approved these changes

2022-05-19 08:05 UTC, merged