Update screen id name for generating new and random address
Bitmessage/PyBitmessage pull request #2029
Opened 2022-08-10 12:22 UTC by shekhar-cis

Update id of random screen; which generate the random identity.

2022-08-11 00:08 UTC, PeterSurda commented
This PR is ok but too small. I'd prefer multiple similar changes in one PR.

2022-08-16 06:18 UTC, shekhar-cis commented
> This PR is ok but too small. I'd prefer multiple similar changes in one PR.

ok

2022-08-17 06:36 UTC, PeterSurda requested changes
normally, the "draft" change would be one PR (or at least one commit), and the id/sc changes would be another one, but for all files together.

2022-08-17 06:36 UTC, PeterSurda commented on src/bitmessagekivy/baseclass/maildetail.py
> -        self.avatarImg = os.path.join(self.kivy_state.imageDir, 'avatar.png') \
just don't use "avatar", this isn't an avatar.

2022-08-17 09:43 UTC, PeterSurda approved these changes

2022-08-19 06:42 UTC, merged