Remove "@skip_screen_checks" to run the test case
Bitmessage/PyBitmessage pull request #2062
Opened 2022-09-02 14:48 UTC by shekhar-cis

Remove "@skip_screen_checks" to run the test case

2022-09-02 15:32 UTC, PeterSurda reviewed
We'll see the results after merging the pending prerequisites.

2022-09-14 05:58 UTC, PeterSurda commented
this needs rebasing

2022-09-19 07:05 UTC, PeterSurda approved these changes

2022-09-30 09:12 UTC, PeterSurda requested changes
instead of commenting out the raise Timeout, change the `break` to `return`

2022-09-30 09:12 UTC, PeterSurda commented on src/bitmessagekivy/tests/test_create_random_address.py
> +    # @ordered
you can just ignore this chunk

2022-09-30 09:13 UTC, PeterSurda commented on src/bitmessagekivy/tests/test_create_random_address.py
> +        self.assertExists("//Screen[0]//MDFillRoundFlatIconButton[@text=\"Proceed Next\"]", timeout=5)
just leave this as it is after fixing the timeout exception

2022-10-04 06:38 UTC, PeterSurda requested changes

2022-10-04 06:38 UTC, PeterSurda commented on src/bitmessagekivy/tests/telenium_process.py
> +            raise AssertionError("Timeout")
this still isn't fixed correctly

2022-10-10 08:09 UTC, shekhar-cis commented on src/bitmessagekivy/tests/telenium_process.py
> +            raise AssertionError("Timeout")
Now is it correct?

2022-10-11 06:50 UTC, PeterSurda approved these changes

2022-10-11 06:51 UTC, merged