Refactor mpybit: Fixed code quality, remove pylint disables and commented code
Bitmessage/PyBitmessage pull request #2068
Opened 2022-09-12 10:00 UTC by shekhar-cis

Refactor mpybit: use `os.path.join`, remove pylint disables

2022-09-14 07:02 UTC, PeterSurda requested changes

2022-09-14 07:02 UTC, PeterSurda commented on src/bitmessagekivy/mpybit.py
> +        top_box_obj.source = os.path.join(self.image_dir, '/default_identicon/{0}.png'.format(curerentAddr))
missing `join`

2022-09-14 07:02 UTC, PeterSurda commented on src/bitmessagekivy/screens_data.json
> +        "Import": "from bitmessagekivy.baseclass.payment import Payment"
add `pybitmessage.`

2022-09-14 12:00 UTC, shekhar-cis commented on src/bitmessagekivy/screens_data.json
> +        "Import": "from bitmessagekivy.baseclass.payment import Payment"
Done

2022-09-14 12:00 UTC, shekhar-cis commented on src/bitmessagekivy/mpybit.py
> +        top_box_obj.source = os.path.join(self.image_dir, '/default_identicon/{0}.png'.format(curerentAddr))
Done

2022-09-14 12:00 UTC, shekhar-cis commented on setup.py
> +                'pybitmessage.bitmessagekivy.tests'
Done

2022-09-15 06:54 UTC, PeterSurda approved these changes

2022-09-15 08:28 UTC, shekhar-cis commented on src/bitmessagekivy/mpybit.py
> +    Window.size = (500, 800)
Done

2022-09-19 07:03 UTC, PeterSurda requested changes

2022-09-19 07:03 UTC, PeterSurda commented on src/bitmessagekivy/mpybit.py
>                  if not os.path.exists(android_path + '/default_identicon/'):
`os.path.join`

2022-09-19 07:03 UTC, PeterSurda commented on src/bitmessagekivy/mpybit.py
> +                    os.path.join(os.environ['ANDROID_PRIVATE'], 'app', 'images', 'kivy/')
I don't like the `/` at the end

2022-09-20 06:39 UTC, PeterSurda requested changes
- unified resolution
- fix `format`

2022-09-20 07:33 UTC, PeterSurda approved these changes
Squash and if all tests pass, I can merge.

2022-09-21 06:32 UTC, PeterSurda approved these changes

2022-09-21 06:41 UTC, merged