Add test cases for network screen
Bitmessage/PyBitmessage pull request #2111
Opened 2022-11-10 09:46 UTC by osamacis

Add test cases for network screen

2022-11-14 06:39 UTC, PeterSurda requested changes

2022-11-14 06:39 UTC, PeterSurda commented on src/bitmessagekivy/tests/test_network_screen.py
> +        self.cli.sleep(1)
replace sleep with something else

2022-11-14 06:39 UTC, PeterSurda commented on src/bitmessagekivy/tests/test_network_screen.py
> +        self.assertExists("//NetworkStat[@name~=\"networkstat\"]", timeout=2)
not sure what this checks

2022-11-14 15:14 UTC, osamacis commented on src/bitmessagekivy/tests/test_network_screen.py
> +        self.assertExists("//NetworkStat[@name~=\"networkstat\"]", timeout=2)
Yes, removed

2022-11-15 13:05 UTC, PeterSurda approved these changes

2022-11-15 13:06 UTC, merged