Refactor mpybit and add msg_composer dropdown
Bitmessage/PyBitmessage pull request #2121
Opened 2022-11-16 13:07 UTC by shekhar-cis

## Repository contributions to the PyBitmessage project

### Description:

- Update in `mpybit.py`: Add `clear_composer()` to reset the fields of composer screen.
- Add `set_navbar_for_composer()` for setting required icons like `send`, `refresh`, `back_arrow`.
- Update `login.py`.
- Update `main.kv`

2022-11-18 06:49 UTC, PeterSurda requested changes

2022-11-18 06:49 UTC, PeterSurda commented on src/bitmessagekivy/baseclass/login.py
> +        self.manager.parent.ids.id_create.children[1].ids.btn.values = []
is this `btn` or was it renamed?

2022-11-18 10:23 UTC, shekhar-cis commented on src/bitmessagekivy/baseclass/login.py
> +        self.manager.parent.ids.id_create.children[1].ids.btn.values = []
Fixed

2022-11-21 06:43 UTC, PeterSurda requested changes
Split into 2 commits. One with the renaming, and one with the new method.

2022-11-22 05:50 UTC, PeterSurda approved these changes

2022-11-23 06:32 UTC, merged