Add show QR-code in myaddress detail screen
Bitmessage/PyBitmessage pull request #2127
Opened 2022-11-21 11:00 UTC by osamacis

Add show QR-code in myaddress detail screen

2022-11-23 06:40 UTC, PeterSurda requested changes
- clean the `sleep`s
- try to use names instead of `[0]` and likes
- try to make the enable/disable test working

2022-11-23 14:53 UTC, osamacis commented
> * clean the `sleep`s
> * try to use names instead of `[0]` and likes
> * try to make the enable/disable test working
Yeah I have tried to replace indexes with text

2022-11-23 23:09 UTC, PeterSurda approved these changes

2022-11-25 06:34 UTC, PeterSurda approved these changes

2022-11-25 06:54 UTC, merged