Kivy baseclass chatscreen
Bitmessage/PyBitmessage pull request #2140
Opened 2022-12-15 14:32 UTC by osamacis

Added a chat screen

2022-12-19 06:53 UTC, PeterSurda commented
Put the "Chat" menu item after the messages, and it its own section. Layout looks ok.

2022-12-20 11:55 UTC, osamacis commented
> Put the "Chat" menu item after the messages, and it its own section. Layout looks ok.

done with it

2022-12-21 06:49 UTC, PeterSurda requested changes

2022-12-21 06:49 UTC, PeterSurda commented on src/bitmessagekivy/baseclass/chat.py
> +    Payment/subscription frontend
change docstring

2022-12-21 06:49 UTC, PeterSurda commented on src/bitmessagekivy/baseclass/chat.py
> +    def __init__(self, *args, **kwargs):
if we just call `super`, we don't need this method

2022-12-24 15:13 UTC, PeterSurda commented
> @PeterSurda
> 
> The words "Chat Screen" and "Chat" bother me.
> 
> **Bitmessage is not a chat application!**
> 
> It should be renamed to something else, such as Discussions.

This is for future functionality. This PR contains initial kivy UI.

2022-12-26 06:38 UTC, PeterSurda approved these changes

2022-12-26 07:05 UTC, PeterSurda commented
@redarmyfaction Can you please explain what specifically is the problem with chat? This isn't a protocol change, this is just a different UI. The whitepaper doesn't talk about the UI.

2022-12-26 07:06 UTC, merged